### ISSUE TITLE
Change one line to make it compatible with the newest Gun version.

### ISSUE THREAD

**Issue by Stefdv** [swifty/gun-p2p-auth#1]
Hey Robert..I'm so bad with Git ;p
@amark released Gun 0.5 as master. However 'key' is depricated so to make gun-p2p-auth  work you will have to change `gun.put(res).key(key)`  into  'gun.get(key).put(res)`

**Comment by robertheessels** [comment]
Thanx. I added your suggestion and released a new version without testing it. (I'm currently very busy working on a totally different project.)
Could you test it for me, please? @Stefdv

**Comment by amark** [comment]
@robertheessels things have been heating up like crazy over here too. When you are free we should chat. Thanks for taking a quick minute out to pull @Stefdv 's updates!

**Comment by Stefdv** [comment]
Robert, tx.  Tested and it works without problems...:)
Tx again for your time. Closing the issue
